jobs:
- job: Centos7
  pool:
    vmImage: 'ubuntu-latest'
  # We use a container to run the build as we must be compatible with centos7's older glibc
  container: rockdreamer/centos7-gcc9:latest
  steps:
  - task: ArtifactoryCollectIssues@1
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      configSource: 'taskConfiguration'
      taskConfig: |
        version: 1
        issues:
          trackerName: JIRA
          regexp: (.*?)\b\(?(Jira|JIRA|jira)?\s+([A-Za-z]{2,5}\d*-\d+)\)?
          keyGroupIndex: 3
          summaryGroupIndex: 1
          trackerUrl: https://jira.ccdc.cam.ac.uk/issues
          aggregate: true
          aggregationStatus: RELEASED
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

  - task: CmdLine@2
    inputs:
      script: 'sudo yum -y install mesa-libGL-devel libX11-devel libXmu-devel unzip'
    displayName: 'Add prerequisites'
  
  # No need to setup specific python, the container's python3 will be used
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: build_conquest_python.py
    displayName: 'install conquest_python'

  # Upload artifactory build info
  - task: ArtifactoryGenericUpload@2
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "$(Build.ArtifactStagingDirectory)/conquest_python*",
              "target": "ccdc-3rdparty-python-interpreters"
            }
          ]
        }
      replaceSpecVars: true
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)-centos7'
      module: 'conquest_python/centos7'
      includeEnvVars: true
      failNoOp: true
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

  - task: ArtifactoryPublishBuildInfo@1
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)-centos7'
      excludeEnvVars: '*password*;*secret*;*key*;*token*;CL_USER;CL_PASSWORD'
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

- job: Ubuntu1804
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: ArtifactoryCollectIssues@1
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      configSource: 'taskConfiguration'
      taskConfig: |
        version: 1
        issues:
          trackerName: JIRA
          regexp: (.*?)\b\(?(Jira|JIRA|jira)?\s+([A-Za-z]{2,5}\d*-\d+)\)?
          keyGroupIndex: 3
          summaryGroupIndex: 1
          trackerUrl: https://jira.ccdc.cam.ac.uk/issues
          aggregate: true
          aggregationStatus: RELEASED
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'
  - task: CmdLine@2
    inputs:
      script: 'sudo apt-get -y install libgl1-mesa-dev libxmuu-dev libx11-dev'
    displayName: 'Add prerequisites'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: build_conquest_python.py
    displayName: 'install conquest_python'

  # Upload artifactory build info
  - task: ArtifactoryGenericUpload@2
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "$(Build.ArtifactStagingDirectory)/conquest_python*",
              "target": "ccdc-3rdparty-python-interpreters"
            }
          ]
        }
      replaceSpecVars: true
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)-ubuntu1804'
      module: 'conquest_python/ubuntu1804'
      includeEnvVars: true
      failNoOp: true
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

  - task: ArtifactoryPublishBuildInfo@1
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)-ubuntu1804'
      excludeEnvVars: '*password*;*secret*;*key*;*token*;CL_USER;CL_PASSWORD'
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:

  - task: ArtifactoryCollectIssues@1
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      configSource: 'taskConfiguration'
      taskConfig: |
        version: 1
        issues:
          trackerName: JIRA
          regexp: (.*?)\b\(?(Jira|JIRA|jira)?\s+([A-Za-z]{2,5}\d*-\d+)\)?
          keyGroupIndex: 3
          summaryGroupIndex: 1
          trackerUrl: https://jira.ccdc.cam.ac.uk/issues
          aggregate: true
          aggregationStatus: RELEASED
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: build_conquest_python.py
    displayName: 'install conquest_python'

  # Upload artifactory build info
  - task: ArtifactoryGenericUpload@2
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "$(Build.ArtifactStagingDirectory)/conquest_python*",
              "target": "ccdc-3rdparty-python-interpreters"
            }
          ]
        }
      replaceSpecVars: true
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)-darwin'
      module: 'conquest_python/darwin'
      includeEnvVars: true
      failNoOp: true
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

  - task: ArtifactoryPublishBuildInfo@1
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)-darwin'
      excludeEnvVars: '*password*;*secret*;*key*;*token*;CL_USER;CL_PASSWORD'
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

- job: WindowsVS2019
  pool:
    vmImage: 'windows-2019'
  variables:
    build_vs_version: '2019'  
  steps:
  - task: ArtifactoryCollectIssues@1
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      configSource: 'taskConfiguration'
      taskConfig: |
        version: 1
        issues:
          trackerName: JIRA
          regexp: (.*?)\b\(?(Jira|JIRA|jira)?\s+([A-Za-z]{2,5}\d*-\d+)\)?
          keyGroupIndex: 3
          summaryGroupIndex: 1
          trackerUrl: https://jira.ccdc.cam.ac.uk/issues
          aggregate: true
          aggregationStatus: RELEASED
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'
  - task: DownloadPackage@1
    inputs:
      packageType: 'upack'
      feed: '5bb2b4cf-422e-43b6-96fe-9c0e119c71d3/2a165bbb-845f-4419-a0ee-dd330924d917'
      view: '5433165f-a013-48d0-93bf-afcdbd9d2b58'
      definition: 'f8aff8d1-6070-4a6c-a751-e481081467a6'
      version: '2.2.0'
      downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download Togl'

  - task: DownloadPackage@1
    inputs:
      packageType: 'upack'
      feed: '5bb2b4cf-422e-43b6-96fe-9c0e119c71d3/2a165bbb-845f-4419-a0ee-dd330924d917'
      view: '5433165f-a013-48d0-93bf-afcdbd9d2b58'
      definition: '250e9026-c0f0-4844-8543-0633b58017ce'
      version: '2.7.18'
      downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download python'
  - task: DownloadPackage@1
    inputs:
      packageType: 'upack'
      feed: '5bb2b4cf-422e-43b6-96fe-9c0e119c71d3/2a165bbb-845f-4419-a0ee-dd330924d917'
      view: '5433165f-a013-48d0-93bf-afcdbd9d2b58'
      definition: '3c07cc42-0842-45b0-8da9-c95149b19bff'
      version: '6.2.6'
      downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download bsddb'
  - task: DownloadPackage@1
    inputs:
      packageType: 'upack'
      feed: '5bb2b4cf-422e-43b6-96fe-9c0e119c71d3/2a165bbb-845f-4419-a0ee-dd330924d917'
      view: '5433165f-a013-48d0-93bf-afcdbd9d2b58'
      definition: '0dd7b46b-5a11-4115-acd0-00e792b27d62'
      version: '3.31.1-r1'
      downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download apsw'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: build_conquest_python.py
    displayName: 'install conquest_python'

  # Upload artifactory build info
  - task: ArtifactoryGenericUpload@2
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "$(Build.ArtifactStagingDirectory)/conquest_python*",
              "target": "ccdc-3rdparty-python-interpreters"
            }
          ]
        }
      replaceSpecVars: true
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)-windows'
      module: 'conquest_python/windows'
      includeEnvVars: true
      failNoOp: true
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'

  - task: ArtifactoryPublishBuildInfo@1
    inputs:
      artifactoryService: 'devops-ccdc-3rd-party'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)-windows'
      excludeEnvVars: '*password*;*secret*;*key*;*token*;CL_USER;CL_PASSWORD'
    env:
      JFROG_CLI_TEMP_DIR: '$(Build.ArtifactStagingDirectory)'
